platform :ios, '8.0'
target :EngineeringInspection do

pod 'Masonry'
pod 'IQKeyboardManager' #iOS8 and later
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'FDFullscreenPopGesture', '1.1'
pod 'WebViewJavascriptBridge', '~> 6.0'
pod 'FTPopOverMenu'
pod 'HSSetTableViewController', '~> 1.3.1'
pod 'WMPageController', '~> 2.5.2'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'SDAutoLayout', '~> 2.2.0'
pod 'REFrostedViewController', '~> 2.4.8'
pod 'PNChart', '~> 0.8.9'
pod 'CLImageEditor/AllTools'

end

