# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def share_pod
    
    pod 'AFNetworking' #网络请求库
    pod 'FDFullscreenPopGesture' #侧滑手势管理
    pod 'IQKeyboardManager' #键盘管理
    pod 'ReactiveObjC' # ReactiveCocoa OC版； 提供函数响应式编程的体验
    pod 'MJExtension' #对象的序列化
    pod 'MBProgressHUD'
    pod 'LCActionSheet' #自定义ActionSheet
    pod 'Masonry' #代码布局
    pod 'MJRefresh'
    pod 'YYText' #富文本排版
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'SDAutoLayout', '~> 2.2.0'
    pod 'WMPageController', '~> 2.5.2'
	    
end

target 'OA_IPAD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OA_IPAD

    share_pod

end

target 'RequestTests' do
    
    share_pod

end
