platform :ios, '8.0'
target :GrapTheOrder do

pod 'Masonry'
pod 'IQKeyboardManager' #iOS8 and later
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'FDFullscreenPopGesture', '1.1'
pod 'WebViewJavascriptBridge', '~> 6.0'
pod 'JPush'
pod 'ReactiveCocoa', '~> 2.5'
pod 'BlocksKit', '~> 2.2.5'
pod 'MJRefresh'
pod 'LeoPayManager', '~> 1.0.0'

end

