platform :ios, '8.0'
target :TheFutureOfManure do

pod 'Masonry'
pod 'IQKeyboardManager' #iOS8 and later
pod 'AFNetworking', '~> 3.2.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'FDFullscreenPopGesture', '1.1'
pod 'WebViewJavascriptBridge', '~> 6.0'
pod 'JPush', '~> 3.0.9'
pod 'ReactiveCocoa', '~> 2.5'
pod 'BlocksKit', '~> 2.2.5'
pod 'MJRefresh'
pod 'LeoPayManager', '~> 1.0.0'
pod 'YYText', '~> 1.0.7'
pod 'OpenShare'

end

