platform :ios, '8.0'
target :WanvePadOA do

pod 'Masonry'
pod 'IQKeyboardManager' #iOS8 and later
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDAutoLayout', '~> 2.2.0'

end

