platform :ios, '8.0'
target :WanveTest do

pod 'Masonry'
pod 'IQKeyboardManager' #iOS8 and later
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FDFullscreenPopGesture', '~> 1.1'

end

